### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by a-waider** [BlazeIsClone/A41SLBOT#18]
**Is your feature request related to a problem? Please describe.**
I'd like to run this project in a container so that I don't have to install it natively. 

**Describe the solution you'd like**
At minimum I would like to have a Docketfile to build the bot. Additionally it would be nice to have the Docker image pushed to a registry.

**Describe alternatives you've considered**
I could build my own Docketfile but I want to improve this project and share what I do. 

**Additional context**

**Comment by BlazeIsClone** [comment]
hey @a-waider currently we are working on migrating to discord.js v13 and will be implementing as a docker image aswell. So will have the ability to run the bot in a container!
