### ISSUE TITLE
WHAT SORCERY IS THIS

### ISSUE THREAD

**Issue by Tetrag11** [BlazeIsClone/A41SLBOT#19]
I TRY PLAY MUSIC MICKAL JACSON BUT I NO HEAR MICKAL JACSON FORM A41SL WHAT THE BLOODY SORCERY IS THIS

**Comment by BlazeIsClone** [comment]
I'm removing this issue as it violates our community guidelines. [CODE OF CONDUCT](https://github.com/BlazeIsClone/A41SLBOT/blob/master/CODE_OF_CONDUCT.md)
